# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6a593e124e47842a347e8dfa4af3dfc9fc9a861b0e03433c2c90c2de8f2d0f8d87ab29c1c56c7e2f7054aa72f83e6f776c46d603eb409a71a5eb49140e69a8

test:
  secret_key_base: 79dc7c25f9ecb974a1f805df6df60e8235f0545ea50eaf2312d0d0870ab73576edc21e63291583eeab6768cd99b75c14760873c46cd226ac74a474b32d21de82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
